# Generated by Django 5.2.13 on 2026-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Вывод средств'), ('rental_payment', 'Оплата аренды'), ('refund', 'Возврат')], default='deposit', max_length=20),
        ),
    ]
