# Generated by Django 6.0.5 on 2026-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_after",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance_before",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
