# Generated by Django 5.1.3 on 2026-06-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Последние 4 цифры карты"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В обработке"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdraw_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вывод",
                "verbose_name_plural": "Заявки на вывод",
                "db_table": "accounts_withdraw_request",
            },
        ),
    ]
