# Generated by Django 5.1.3 on 2026-06-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_withdrawrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="balance",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="WithdrawRequest",
        ),
    ]
