# Generated by Django 6.0.5 on 2026-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="deposit_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="price_per_hour",
            field=models.FloatField(default=0),
        ),
    ]
