# Generated by Django 6.0.5 on 2026-05-27 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_item_deposit_amount_alter_item_price_per_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="deposit_amount",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Залог не может быть отрицательным"
                    ),
                    django.core.validators.MaxValueValidator(
                        500000, "Залог не может превышать 500 000 ₽"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="main_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="items/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price_per_hour",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Цена не может быть отрицательной"
                    ),
                    django.core.validators.MaxValueValidator(
                        100000, "Цена не может превышать 100 000 ₽ в час"
                    ),
                ],
            ),
        ),
    ]
