# Generated by Django 5.2.13 on 2026-05-13 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('in_progress', 'В процессе аренды'), ('waiting_return', 'Ожидает возврата'), ('completed', 'Завершена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена'), ('disputed', 'Спор')], default='pending', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('needs_moderation', models.BooleanField(default=False)),
                ('rental_paid', models.BooleanField(default=False)),
                ('renter_received', models.BooleanField(default=False)),
                ('owner_return_confirmed', models.BooleanField(default=False)),
                ('deposit_frozen', models.BooleanField(default=False)),
                ('deposit_returned', models.BooleanField(default=False)),
                ('deposit_to_owner', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('damage_photo', models.ImageField(blank=True, null=True, upload_to='damages/')),
                ('damage_video', models.FileField(blank=True, null=True, upload_to='damages/')),
                ('dispute_created_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
