# Generated by Django 5.2.13 on 2026-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_given_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_given_by_renter',
            field=models.BooleanField(default=False),
        ),
    ]
