# Generated by Django 6.0.5 on 2026-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_review_given_by_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="deposit_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price_per_hour",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_hours",
            field=models.FloatField(default=0),
        ),
    ]
