# Generated by Django 5.1.3 on 2026-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_confirmed_by_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_confirmed_by_renter",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает подтверждения"),
                    ("confirmed", "Подтверждена"),
                    ("waiting_payment", "Ожидает оплаты"),
                    ("waiting_payment_confirmation", "Ожидает подтверждения оплаты"),
                    ("in_progress", "В процессе аренды"),
                    ("waiting_return", "Ожидает возврата"),
                    ("waiting_refund", "Ожидает возврата залога"),
                    (
                        "waiting_refund_confirmation",
                        "Ожидает подтверждения возврата залога",
                    ),
                    ("completed", "Завершена"),
                    ("rejected", "Отклонена"),
                    ("cancelled", "Отменена"),
                    ("disputed", "Спор"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
